### ISSUE TITLE
Synatx issue in application.cfc

### ISSUE THREAD

**Issue by gregorythrush** [dezoito/fw1-clipping#1]
Trying to run your application in my test environment, CF9.x throws an error:

Invalid construct.

A script statement must end with ";".
The CFML compiler was processing:

A script statement beginning with this.customTagPaths on line 21, column 5.

The error occurred in C:\serve\www\testing.etr.org\fw1Clipping\Application.cfc: line 21
19 : 
20 :     this.mappings["/root"] = getDirectoryFromPath(getCurrentTemplatePath());
21 :     this.customTagPaths = this.mappings["/root"] & "customtags"
22 :     this.triggerDataMember = true // so we can access properties directly (no need for getters and setters)
23 :

**Comment by dezoito** [comment]
Fixes pushed on commit 6905e13f17695ddf15f309e00f78075cfc34fba7.

The lack of ";" was not generating errors on environments used for testing, which would have been desirable (note that it was NOT tested on anything but Railo up to this point).

Thank you for pointing the error.
